services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Cấu hình kết nối đến DB trên cloud
      - DATABASE_HOST=217.142.224.197
      - DATABASE_PORT=5432
      - DATABASE_NAME=aniself
      - DATABASE_USERNAME=master
      - DATABASE_PASSWORD=doanhanma
